### ISSUE TITLE
No synset found

### ISSUE THREAD

**Issue by smoes** [sarschu/refuCat#1]
MongoDB läuft:

```
>>> from categorizer import Categorizer
>>> c = Categorizer()
>>> 
>>> c.categorize_word('word')
Word
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "categorizer.py", line 168, in categorize_word
    cats = self._collect_category(word)
  File "categorizer.py", line 36, in _collect_category
    categories_gn = self._add_germanet_categories(unicode(word))    
  File "categorizer.py", line 62, in _add_germanet_categories
    hp = gn.synset(word+'.n.1').hypernym_paths
AttributeError: 'NoneType' object has no attribute 'hypernym_paths'
>>> 
>>> 
```

**Comment by sarschu** [comment]
word ist kein deutsches Wort. Aber stimmt, da muss ein Abfängerle rein

**Comment by smoes** [comment]
Weder `Stuhl`, `Schrank` oder `Tisch` tun :-1:

**Comment by sarschu** [comment]
oO

**Comment by sarschu** [comment]
Dann klappt das nicht mit der db-Übertragung. Bei mir gehts

**Comment by sarschu** [comment]
Im Wiki ist der Link zu pygermanet. Versuch mal bitte, wenn mongodb läuft, die direkte Funktionalität von pygermanet zu benutzen. dann wissen wir, ob es daran liegt

**Comment by smoes** [comment]
Kann ich wie bei pygermanet starten und die DB bekommt ne Connection, aber bei den synsets im Beispiel sind die Listen leer. Hab ich irgendnen Corpus oder sowas nicht installiert?

**Comment by sarschu** [comment]
Naja, ich hab dir Germanet nicht gegeben, weil ich das hier nicht hochladen wollte wegen Lizenzen und so. Aber ich dachte, da ich das ja wie bei pygermanet beschrieben in diesen mongodb-Ordner geladen hab, dass das geht. Und ich hab jetzt das Projekt hier auch ausgecheckt und in dem Ordner läufts auch, obwohl da auch nur der db-Ordner liegt

**Comment by sarschu** [comment]
python -m pygermanet.mongo_import ~/corpora/germanet/GN_V80/GN_V80_XML/

muss hieran liegen...
